version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
