version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root
    command: ["redis-server", "--requirepass", "root"]
    volumes:
      - ./storage/redis:/data
